version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy:
    # steps:
    #   - add_ssh_keys:
    #     fingerprints:
    #      - "73:c4:69:73:80:6c:cf:ed:d1:12:15:ba:dd:eb:f7:03"
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "sh ./domains/hello.marian.fun/deploy.sh"

workflows:
  build-and-deploy:
    jobs:
      - build-and-test
      - deploy
        requires:
          - build-and-test
        filters:
          branches:
           only: master
